[package]
name = "ulneron"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.0"
bincode = "1.3.3"
fastrand = "1.8.0"
serde = { version = "1.0.143", features = ["derive"] }
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
